---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hades.github.com
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hades.github.com
  resources:
  - cronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - hades.github.com
  resources:
  - cronjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hades.github.com
  resources:
  - soles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hades.github.com
  resources:
  - soles/finalizers
  verbs:
  - update
- apiGroups:
  - hades.github.com
  resources:
  - soles/status
  verbs:
  - get
  - patch
  - update
