# permissions for end users to edit soles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sole-editor-role
rules:
- apiGroups:
  - hades.amirhnajafiz.github.com
  resources:
  - soles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hades.amirhnajafiz.github.com
  resources:
  - soles/status
  verbs:
  - get
